import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  orchestraSidebar: [
    'index',
    'roadmap',
    {
      type: 'category',
      label: 'Milestones',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'milestones'}],
    },
    {
      type: 'category',
      label: 'Decisions',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'decisions'}],
    },
    {
      type: 'category',
      label: 'Devlog',
      items: [{type: 'autogenerated', dirName: 'devlog'}],
    },
    {
      type: 'category',
      label: 'Learning',
      items: [{type: 'autogenerated', dirName: 'learning'}],
    },
  ],
};

export default sidebars;
